# Generated by Django 3.1b1 on 2020-07-13 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComapnyStockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, verbose_name='Ticker Name')),
                ('company_name', models.CharField(max_length=150, verbose_name='Company Name')),
                ('stock_exchange', models.CharField(max_length=20, verbose_name='Stock Exchange')),
            ],
        ),
        migrations.CreateModel(
            name='StockDayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Close Price')),
                ('volume', models.IntegerField(verbose_name='Close Volume')),
                ('company_stock_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_app.comapnystockdata')),
            ],
        ),
    ]
