# Generated by Django 3.1b1 on 2020-07-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comapnystockdata',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='update_time'),
        ),
    ]
