# Generated by Django 3.1b1 on 2020-07-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0002_comapnystockdata_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdaydata',
            name='stock_date',
            field=models.DateField(auto_now=True, verbose_name='stock_date'),
        ),
        migrations.AlterField(
            model_name='comapnystockdata',
            name='update_time',
            field=models.DateField(auto_now=True, verbose_name='update_time'),
        ),
    ]
