# Generated by Django 3.1b1 on 2020-07-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0005_auto_20200714_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdaydata',
            name='stock_date',
            field=models.DateField(verbose_name='stock_date'),
        ),
    ]
