# Generated by Django 3.1b1 on 2020-07-16 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0006_auto_20200714_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdaydata',
            name='company_stock_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_by', to='Main_app.comapnystockdata'),
        ),
    ]
