# Generated by Django 3.1b1 on 2020-07-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0007_auto_20200716_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdaydata',
            name='volume',
            field=models.IntegerField(db_index=True, verbose_name='Close Volume'),
        ),
    ]
