# Generated by Django 3.1b1 on 2020-07-13 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OBVindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_change', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Percentage Change')),
                ('volume_change', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Volume Amount Change')),
                ('company_stock_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_app.comapnystockdata')),
            ],
        ),
    ]
