# Generated by Django 3.1b1 on 2020-07-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBVapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obvindex',
            old_name='volume_change',
            new_name='obv',
        ),
    ]
