# Generated by Django 3.1b1 on 2020-07-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBVapp', '0002_auto_20200715_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obvindex',
            options={'verbose_name': 'OBV Stock', 'verbose_name_plural': 'OBV Index Stock'},
        ),
    ]
